# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, unique=True)),
                ('description', models.TextField(blank=True, max_length=25, null=True)),
                ('date', models.DateField()),
                ('frequency', models.CharField(choices=[('ON', 'once'), ('YE', 'yearly')], default='YE', max_length=2)),
            ],
        ),
    ]
